#!/bin/sh
set -eu

echo "---------- Git hook: pre-commit ----------"

echo ">>> [1/3] Running biome"
pnpm biome:check

echo ">>> [2/3] Running tsc"
pnpm tsc

echo ">>> [3/3] Running tests"
pnpm test

echo "------------------------------------------"
