version: '3'

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml

vars:
  APP_NAME: "ClickLaunch"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "darwin:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "darwin:package"

  run:
    summary: Runs the application
    cmds:
      - task: "darwin:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  lint:
    summary: Runs all linters (biome, tsc, golangci-lint)
    cmds:
      - bun run biome:check
      - bun run tsc
      - golangci-lint run

  test:
    summary: Runs all tests
    cmds:
      - go test -race ./backend/...

  check:
    summary: Runs all quality checks (lint + test)
    cmds:
      - task: lint
      - task: test

  clean:
    summary: Removes build artifacts
    cmds:
      - rm -rf dist bin

  version:bump:
    summary: Bumps the app version across all config files
    cmds:
      - sh scripts/bump-version.sh {{.CLI_ARGS}}
